using TdSharp.Core;
using TdSharp.Transpiler;

namespace TdSharp.Tests;

public class TranspilerTests
{
    private static string Transpile(string source)
    {
        var lexer = new Lexer(source);
        var tokens = lexer.Tokenize();
        var parser = new Parser(tokens);
        var program = parser.Parse();
        var transpiler = new AstTranspiler();
        return transpiler.Transpile(program);
    }

    [Fact]
    public void Transpiles_EmptyProgram()
    {
        var result = Transpile("");
        Assert.Contains("Generated by Td#", result);
    }

    [Fact]
    public void Transpiles_SayStatement()
    {
        var result = Transpile("say(\"hello\")");
        Assert.Contains("tds_say", result);
        Assert.Contains("hello", result);
    }

    [Fact]
    public void Transpiles_VariableDeclaration()
    {
        var result = Transpile("var x = 42");
        Assert.Contains("x = 42", result);
    }

    [Fact]
    public void Transpiles_ConstDeclaration()
    {
        var result = Transpile("const PI = 3.14");
        Assert.Contains("PI = 3.14", result);
    }

    [Fact]
    public void Transpiles_IfStatement()
    {
        var result = Transpile("if x > 5 then say(\"big\") end");
        Assert.Contains("if", result);
        Assert.Contains("then", result);
        Assert.Contains("end", result);
    }

    [Fact]
    public void Transpiles_IfElseStatement()
    {
        var result = Transpile("if x > 5 then say(\"big\") else say(\"small\") end");
        Assert.Contains("if", result);
        Assert.Contains("else", result);
        Assert.Contains("end", result);
    }

    [Fact]
    public void Transpiles_WhileLoop()
    {
        var result = Transpile("while x > 0 do x = x - 1 end");
        Assert.Contains("while", result);
        Assert.Contains("do", result);
        Assert.Contains("end", result);
    }

    [Fact]
    public void Transpiles_ForLoop()
    {
        var result = Transpile("for i = 1 to 10 do say(i) end");
        Assert.Contains("for", result);
        Assert.Contains("=", result);
        Assert.Contains("do", result);
        Assert.Contains("end", result);
    }

    [Fact]
    public void Transpiles_FunctionDeclaration()
    {
        var result = Transpile("function greet(name) say(name) end");
        Assert.Contains("function", result);
        Assert.Contains("greet", result);
        Assert.Contains("end", result);
    }

    [Fact]
    public void Transpiles_BinaryExpression()
    {
        var result = Transpile("var x = 1 + 2");
        Assert.Contains("(1 + 2)", result);
    }

    [Fact]
    public void Transpiles_Comparison()
    {
        var result = Transpile("var eq = a == b");
        Assert.Contains("(a == b)", result);
    }

    [Fact]
    public void Transpiles_NotExpression()
    {
        var result = Transpile("var n = not flag");
        Assert.Contains("(not flag)", result);
    }

    [Fact]
    public void Transpiles_NilLiteral()
    {
        var result = Transpile("var n = nil");
        Assert.Contains("nil", result);
    }

    [Fact]
    public void Transpiles_BoolLiteral()
    {
        var result = Transpile("var t = true\nvar f = false");
        Assert.Contains("true", result);
        Assert.Contains("false", result);
    }

    [Fact]
    public void Transpiles_StringLiteral()
    {
        var result = Transpile("var s = \"hello world\"");
        Assert.Contains("\"hello world\"", result);
    }

    [Fact]
    public void Transpiles_ClassDeclaration()
    {
        var result = Transpile("class Player x=100 y=200 end");
        Assert.Contains("-- Class:", result);
        Assert.Contains("Player", result);
        Assert.Contains("__index", result);
    }

    [Fact]
    public void Transpiles_ReturnStatement()
    {
        var result = Transpile("function add(a,b) return a + b end");
        Assert.Contains("return", result);
    }

    [Fact]
    public void Transpiles_ForEachLoop()
    {
        var result = Transpile("for item in items do say(item) end");
        Assert.Contains("for _,", result);
        Assert.Contains("in ipairs", result);
    }

    [Fact]
    public void Transpiles_BreakStatement()
    {
        var result = Transpile("while true do break end");
        Assert.Contains("break", result);
    }

    [Fact]
    public void Transpiles_MathBuiltins()
    {
        var result = Transpile("var m = abs(-5)");
        Assert.Contains("tds_abs", result);
    }

    [Fact]
    public void Transpiles_ArrayLiteral()
    {
        var result = Transpile("var arr = [1, 2, 3]");
        Assert.Contains("{1, 2, 3}", result);
    }

    [Fact]
    public void Transpiles_MapLiteral()
    {
        var result = Transpile("var m = {a = 1, b = 2}");
        Assert.Contains("a = 1", result);
        Assert.Contains("b = 2", result);
    }
}
